version: "3.9"

services:
  redis:
    image: redis:7.2
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --user ${REDIS_USER} on >${REDIS_PASSWORD} allcommands allkeys
    env_file:
      - .env
    volumes:
      - redis_data:/data

volumes:
  redis_data:
